services:
  # data-etl:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ["python", "-m", "src.main"]
  #   env_file:
  #     - .env
  #   volumes:  # TODO: remove in production
  #     - ${CONFIG_PATH}:/app/config.json
  #   working_dir: /app
  #   environment:
  #     CONFIG_PATH: /app/config.json
  qdrant:
    image: qdrant/qdrant:latest
    profiles:
      - qdrant_vectorstore
    ports:
      - "6333:6333"    # HTTP API
      - "6334:6334"    # gRPC API
    volumes:
      - ${INDEX_ROOT}/qdrant_storage:/qdrant/storage
      - ${INDEX_ROOT}/qdrant_config/data-etl:/qdrant/config
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__ENABLE_CORS=true
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "timeout 2 bash -c 'cat < /dev/null > /dev/tcp/localhost/6333' || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  ollama:
    image: ollama/ollama:latest
    profiles:
      - ollama_embeddings
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

volumes:
    ollama: {}